:toc:
:toc-placement!:

= Field types: Aspects and assumptions shared across types

toc::[]

== `type` property

Is always an entity reference to a taxonomy term.

Behaviors triggered by the `type` property assume its value is a taxonomy term.

The presence of values in taxonomy term fields beyond `name` play into this field/property's behavior, so new terms should be created in the relevant taxonomies directly---not by typing them in as "types" in node metadata.

Because these terms have impact on system behavior, it does not seem unreasonable to require their creation to involve metadata manager role or at least a separate workflow process.

=== Field configuration

- Ability to select which vocabulary (or vocabularies) may be used
- No need to include "Create referenced entities if they don't already exist" option
- Ability to use default entity reference or filter by an entity reference view (e.g. Active taxonomy terms)

=== Form widget

- Most of these vocabularies are relatively small, so a dropdown works better, as it shows the available choices

=== Display formatter

- Entity reference should be rendered as unlinked term name (in the case of identifier types, it is not helpful to click on "ISBN" and be taken to that taxonomy term page)

