:toc:
:toc-placement!:

= Field type: Typed, labeled title

Think of this as basically a version of the Typed, labeled text fields. The difference is the `value` property is broken down into some more granular parts: nonsort, title, subtitle, partname, partnumber.

The parts need to be concatenated together (with appropriate punctuation in between) in two slightly different ways for indexing the sort title and display.

I am not currently seeing much extra behavior dependent upon the properties in Islandora. The need for this structure is more about not losing metadata granularity (keeping it interoperable with common standard metadata schema) and for ease of migration.

toc::[]

== Schema

[cols=3*,options=header]
|===
| Property name | Data type | Required?
| nonsort | Text (plain) | n
| title | Text (plain) | y
| subtitle | Text (plain) | n
| partname | Text (plain) | n
| partnumber | Text (plain) | n
| label | Text (plain) | n
| type  | Entity reference to taxonomy term | n
|===

`title` is the only required property. When filling out a form with an instance of this field, a user can leave every part blank except `title`.

We can rename the `title` property to something else if it is too confusing...

=== Property data types (length)

Maximum length of valid values in each MODS element that will map to our field type properties.

* nonsort - 8
* title - 639
* subtitle - 407
* partnumber - 114
* partname - 415

Takeaway: These do not have to allow full on paragraphs of text, but title, subtitle, and partname need to be longer than 255 characters.

=== Nonsort - no stripping of trailing spaces

If there are trailing spaces on the nonsort values, they must be maintained.

It is ok (but not necessarily required) to strip trailing spaces off the other properties.

=== Omission of `primary` property

We had discussed the need to include a boolean `primary` property in our Typed, labeled title field type. This property would be required if more than one value were entered in the field, and you could only check it on one value in a given field.

The value marked primary would be used as the sort title, would be output as the main title in OAI-PMH/generated citations, and basically get special treatment whenever one title was needed to be used for some functionality.

After reviewing all our clients' current MODS data, only 3 records (out of 252,147) have tagged the not-recorded-first title as primary. After reviewing those 3 records, I see no reason why the primary title isn't the first one in the record.

*We will assume the first title value recorded is to be treated as the primary title in any parts of the system that require such a thing.*

[IMPORTANT]
====
If a user changes the order of title values in a record, the change of which title is primary should cascade through all the places that indication matters: indexing for sort, etc.
====

== Field configuration options

* See https://github.com/lyrasis/islandora8-metadata/blob/main/field_types/_all_typed_fields.adoc[All "typed" field types > Field configuration options]
* See https://github.com/lyrasis/islandora8-metadata/blob/main/field_types/_all_labeled_fields.adoc[All "labeled" field types > Field configuration options]

* Storage
** field repeatability (1, a specific number of times, unlimited)
** `value` length (up to 255)
* Other field configuration options
** nothing extra beyond what comes with typed and labeled field types

== Form view options
None initially required, but I really like the Name Field's compact (inline) option.

The "Widget settings" (stacked vs. inline) are https://default.traefik.me/admin/structure/taxonomy/manage/person/overview/fields/taxonomy_term.person.field_person_preferred_name[here]. See the effect https://default.traefik.me/admin/structure/taxonomy/manage/person/add[here] (expand Name Details section).

== Display formatter options

* See https://github.com/lyrasis/islandora8-metadata/blob/main/field_types/all_typed_and_labeled_fields.adoc[Field types: Stuff shared by all field types having both type and label properties > Display formatter options & examples]

=== Rules for concatenating properties for display

* Order of concatenation: `nonsort`, `title`, `subtitle`, `partnumber`, `partname`
* No characters or spaces inserted between `nonsort` and `title`

.Example 1a
[source,xml]
----
<titleInfo>
  <nonSort>The ... </nonSort>
  <title>Oregon population survey</title>
</titleInfo>
----

Should become:

`The ... Oregon population survey`

NOT:

`The ...Oregon population survey`

.Example 1b
[source,xml]
----
<titleInfo>
  <nonSort>The "</nonSort>
  <title>Red Hill" soils of western Oregon and their utilization</title>
</titleInfo>
----

Should become:

`The "Red Hill" soils of western Oregon and their utilization`

NOT:

`The " Red Hill" soils of western Oregon and their utilization`

* If there is a `subtitle` value, prepend ``: ``, but handle the case that sometimes the ``:``  may have been hard-coded onto the end of the `title` value

.Example 2a
[source,xml]
----
<titleInfo>
  <nonSort>An </nonSort>
  <title>essay on electricity</title>
  <subTitle>being an enquiry into the nature, cause and properties thereof, on the principles of Sir Issac Newton's theory of vibrating motion, light and fire ; and the various phænomena of fourty-two capitl experiments ; with some observations relative to the uses that may be made of this wonderful power of nature</subTitle>
</titleInfo>
----

Should become:

`An essay on electricity: being an enquiry into the nature, cause and properties thereof, on the principles of Sir Issac Newton's theory of vibrating motion, light and fire ; and the various phænomena of fourty-two capitl experiments ; with some observations relative to the uses that may be made of this wonderful power of nature`

.Example 2b
[source,xml]
----
<titleInfo type="alternative">
  <title>Research project work plan for multi-modal intersections :</title>
  <subTitle>resolving conflicts between trains, motor vehicles, bicyclists and pedestrians</subTitle>
</titleInfo>
----

Should become:

`Research project work plan for multi-modal intersections: resolving conflicts between trains, motor vehicles, bicyclists and pedestrians`

* If there is a `partnumber` value...
** And the final non-space character of preceding string is: `…`, `.`, `!`, `-`, or `?`, prepend a space to `partnumber`
** And the final non-space character of preceding string is anything else, prepend ``. `` to `partnumber`

.Example 3a
[source,xml]
----
<titleInfo>
  <title>Water primrose, Ludwigia spp., aquatic invader!</title>
  <partNumber>Series 2</partNumber>
</titleInfo>
----

Should become:

`Water primrose, Ludwigia spp., aquatic invader! Series 2`

.Example 3b
[source,xml]
----
<titleInfo usage="primary">
  <title>Rear, left and right side elevations</title>
  <subTitle>Residential house plans</subTitle>
  <partNumber>3 of 3</partNumber>
</titleInfo>
----

Should become:

`Rear, left and right side elevations: Residential house plans. 3 of 3`

== Indexing options

* See https://github.com/lyrasis/islandora8-metadata/blob/main/field_types/all_typed_and_labeled_fields.adoc[Field types: Stuff shared by all field types having both type and label properties > Indexing options & examples]



