:toc:
:toc-placement!:
:toclevels: 4

= MODS originInfo migration examples

toc::[]

Here I'm trying to verify that my field type and data mapping plans are workable. I'm finding the most complex and sometimes weird MODS originInfo data that I can and verifying that I can map it as expected.

To look up client number references, see internal metadata_profiling_details.xlsx -> profiling tab.

Some values in the example MODS have been changed so it's less obvious who the data belongs to.

== General setup assumptions
=== Taxonomy vocabularies

* Origin event types
* Date types
* Place types
* Agent roles
* Modes of issuance
* Frequencies
* Place
** has field: External vocabulary code
* Organization
* Person
* Family

== Field definition assumptions

[IMPORTANT]
====
There is a conditional `Primary date field` displayed in form when more than one date field is populated.

The first value from the field selected as `Primary date field` will be used as sort date and for any other system functions requiring a single date value per record.
====

=== Field: Origin statement

Field type: origin_statement

Field type properties:

* type - entity reference (Origin event types)
* label - text
* place - text
* agent - text
* date - text
* addtl - text

=== Field: Publisher

Field type: typed, labeled entity reference

Field type properties:

* type - entity reference (Agent roles)
* label - text
* value - entity reference (Organization, Person, or Family)

[NOTE]
====
If type is set to Distributor or Manufacturer, the field label will change to say that instead of Publisher.
====

=== Field: Origin place

Field type: typed, labeled entity reference

Field type properties:

* type - entity reference (Place types)
* label - text
* value - entity reference (Place)

=== Field: Mode of issuance

Field type: labeled entity reference

Field type properties:

* label - text
* value - entity reference (Modes of issuance)

=== Field: Frequency

Field type: labeled entity reference

Field type properties:

* label - text
* value - entity reference (Frequencies)

=== Field: Issued date

Field type: EDTF date

=== Field: Creation date

Field type: EDTF date

=== Field: Copyright date

Field type: EDTF date

=== Field: Capture date

May be renamed "Digitization date"

Field type: EDTF date

=== Field: Donated date

Likely a client-specific field

Field type: EDTF date

== Examples

=== client12:51569

[source,xml]
----
<originInfo>
  <place>
    <placeTerm type="code" authority="marccountry">oru</placeTerm>
  </place>
  <dateIssued encoding="marc" point="start">uuuu</dateIssued>
  <dateIssued encoding="marc" point="end">9999</dateIssued>
  <issuance>serial</issuance>
  <frequency authority="marcfrequency">Annual</frequency>
  <frequency>Annual</frequency>
</originInfo>
<originInfo displayLabel="publisher">
  <place>
    <placeTerm type="text">&lt;2004&gt;-2010:[Portland, Oregon] :[Oregon Center for Health Statistics]</placeTerm>
  </place>
  <publisher>[Oregon Center for Health Statistics]</publisher>
  <dateIssued/>
</originInfo>
<originInfo displayLabel="publisher">
  <place>
    <placeTerm type="text">2011- :[Portland, Oregon] :[Health Statistics Unit, Vital Records]</placeTerm>
  </place>
  <publisher>[Health Statistics Unit, Vital Records]</publisher>
  <dateIssued/>
</originInfo>
----

Origin statement:

* [0]
** type: Publication
** label: <2004>-2010
** place: [Portland, Oregon]
** agent: [Oregon Center for Health Statistics]
* [1]
** type: Publication
** label: 2011-
** place: [Portland, Oregon]
** agent: [Health Statistics Unit, Vital Records]

Origin place:

* [0]
** value: Oregon
* [1]
** type: Place of publication
** value: Portland, Oregon

Origin agent:

* [0]
** type: Publisher
** value: Oregon Center for Health Statistics
* [1]
** type: Publisher
** value: Health Statistics Unit, Vital Records


Issued date:

* [0]
** value: /..

Mode of issuance:

* [0]
** value: serial

Frequency:

* [0]
** value: annual

Primary date field value:

* /..


=== client12:23046

[source,xml]
----
<originInfo>
  <place>
    <placeTerm type="code" authority="marccountry">idu</placeTerm>
  </place>
  <place>
    <placeTerm type="text">[Moscow, Idaho]</placeTerm>
  </place>
  <place>
    <placeTerm type="text">[Corvallis, Or.]</placeTerm>
  </place>
  <place>
    <placeTerm type="text">[Pullman, Wash.]</placeTerm>
  </place>
  <place>
    <placeTerm type="text">[Washington, D.C.]</placeTerm>
  </place>
  <publisher>University of Idaho Cooperative Extension System</publisher>
  <publisher>Oregon State University Extension Service</publisher>
  <publisher>Washington State University Cooperative Extension</publisher>
  <publisher>U.S. Dept. of Agriculture</publisher>
  <dateIssued>c2006</dateIssued>
  <dateIssued encoding="marc">2006</dateIssued>
  <issuance>monographic</issuance>
</originInfo>
---

Origin statement:

* [0]
** place: [Moscow, Idaho]
** agent: University of Idaho Cooperative Extension System
* [1]
** place: [Corvallis, Or.]
** agent: Oregon State University Extension Service
* [2]
** place: [Pullman, Wash.]
** agent: Washington State University Cooperative Extension
* [3]
** place: [Washington, D.C.]
** agent: U.S. Dept. of Agriculture

Origin place:

* [0]
** value: Idaho
* [1]
** value: Moscow, Idaho
* [2]
** value: Corvallis, Or.
* [3]
** value: Pullman, Wash.
* [4]
** value: Washington, D.C.

Origin agent:

* [0]
** value: University of Idaho Cooperative Extension System
* [1]
** value: Oregon State University Extension Service
* [2]
** value: Washington State University Cooperative Extension
* [3]
** value: U.S. Dept. of Agriculture

Copyright date:

* [0]
** value: 2006

Issued date:

* [0]
** value: 2006

Mode of issuance:

* [0]
** value: monograph

Primary date field value:

* 2006

=== client21:38537

[source,xml]
----
<originInfo>
  <dateCaptured>2008</dateCaptured>
  <dateIssued keyDate="yes">1973-04</dateIssued>
  <publisher>Acme Publisher</publisher>
  <place>
    <placeTerm type="text">Richmond, Va</placeTerm>
  </place>
</originInfo>
----

Origin statement:

* [0]
** place: Richmond, Va
** agent: Acme Publisher

Origin place:

* [0]
** value: Richmond, Va

Origin agent:

* [0]
** value: Acme Publisher

Issued date:

* [0]
** value: 1973-04

Capture date:

* [0]
** value: 2008

Primary date field value:

* 1973-04

=== client6:9685

[source,xml]
----
<originInfo>
  <publisher>Super Publisher</publisher>
  <copyrightDate>March 28, 1916</copyrightDate>
  <dateCaptured>Digitized:  04/27/2004</dateCaptured>
  <dateOther>Donated:  05/08/1997</dateOther>
  <dateCreated>c. 1916</dateCreated>
</originInfo>
----

Origin agent:

* [0]
** value: Super Agent

Copyright date:

* [0]
** value: 1916-03-28

Capture date:

* [0]
** value: 2004-04-27

Donated date:

* [0]
** value: 1997-05-08

Creation date:

* [0]
** value: 1916~

Primary date field value:

* 1916~

=== ?

[source,xml]
----
<originInfo script="Latn" altRepGroup="02">
  <place>
    <placeTerm type="code" authority="marccountry">sp</placeTerm>
  </place>
  <place>
    <placeTerm type="text">Ṿadi Alḥagarah</placeTerm>
  </place>
  <publisher>Shelomoh Alḳabets</publisher>
  <dateIssued>242, 1482]</dateIssued>
  <dateIssued encoding="marc">1482</dateIssued>
  <issuance>monographic</issuance>
</originInfo>
<originInfo script="Hebr" altRepGroup="02">
  <place>
    <placeTerm type="text">[ואדי אלחגארה :</placeTerm>
  </place>
  <publisher>שלמה אלקבץ,</publisher>
  <dateIssued>רמ"ב, 1482]</dateIssued>
</originInfo>
----


=== client12:?

[source,xml]
----
<originInfo>
  <place>
    <placeTerm type="code" authority="marccountry">oru</placeTerm>
  </place>
  <dateIssued encoding="marc">1911</dateIssued>
  <issuance>monographic</issuance>
</originInfo>
<originInfo displayLabel="publisher">
  <place>
    <placeTerm type="text">[Salem, Oregon] :[Office of the Governor],[1911]</placeTerm>
  </place>
  <publisher>[Office of the Governor],</publisher>
  <dateIssued>[1911]</dateIssued>
</originInfo>
<originInfo displayLabel="manufacturer">
  <place>
    <placeTerm>Salem, Oregon :</placeTerm>
  </place>
  <publisher>Willis S. Duniway, State Printer,</publisher>
  <dateOther type="manufacture">1911</dateOther>
</originInfo>
----


== Pre-migration data transformation algorithm notes

These are completely untested at this point, but I want to start capturing ideas about what the required logic might be.

I expect these to definitely be client-specific, and likely at least sometimes collection-specific. If we are lucky, most of the complex stuff will follow patterns of how data was mapped to MODS in migration to I7, but there will probably also be all manner of fun variation in practice to account for.

=== population of origin statement field
==== within one `originInfo` element, at least two of the following: `placeTerm` with `type = text`, `publisher`, `dateIssued`

Applies to example(s): client12:51569, client12:23046

Populate origin statement field

==== within one `originInfo` element, multiple `placeTerm` and `publisher` elements with equal count for each

Applies to example(s): client12:23046

Match `placeTerm` and `publisher` element values by order/position to populate multiple origin statements

==== not populating origin statement field

applies to example(s):

* client6:9685 - only one of the required elements present


=== originInfo/placeTerm -> origin statement - extract place from placeTerm

applies to example(s): client12:51569

* within a given `originInfo` element, clean up `placeTerm` value by:
** remove the `publisher` value from the `placeTerm` value
** remove any date element value from the `placeTerm` value
** strip trailing : and space from `placeTerm` value
** split `placeTerm` value on `:`
** if length of resulting array >= 2
*** element[0] = label value
*** other elements, joined back together with `:` = place value
** if length of resulting array < 2
*** the sole element = place value

=== originInfo/placeTerm (type = text or blank) -> Place taxonomy term

applies to example(s): client12:51569

* remove square brackets from around value
* remove any trailing funky punctuation

=== originInfo/placeTerm (type = code and authority = marccountry) -> Place taxonomy term

applies to example(s): client12:51569

Gotta make some decisions. I do *not* want to maintain a separate MARC countries code vocabulary as comes with controlled_access_terms

I *may* just prepopulate the default Places taxonomy with the entire MARC countries vocabulary term set, transformed from the current available data set + a migration.

If not, during migration, the first step will be to populate Places taxonomy with all needed terms:

* look up code value (oru) in LC marccountries API
* get textual label (Oregon)
* get term URI (http://id.loc.gov/vocabulary/countries/oru)
* create taxonomy term with the following mappings:
** name: textual label (Oregon)
** field_term_uri: http://id.loc.gov/vocabulary/countries/oru
** field_external_vocabulary_source: MARC Countries
** field_external_vocabulary_code: oru

Then, while migrating the data for each node:

* migration looks up taxonomy term from Places vocabulary using `originInfo/placeTerm` value = `field_external_vocabulary_code` value
* entity reference to term Oregon is made in the node field

=== originInfo/date values

==== how to set conditional `Primary date field` value in migration?

applies to example(s): any with more than one date field populated

NOTE: It is clear which date field to use as `Primary date field` when `keyDate` attribute is set in MODS. We will need to come up with a priority ranking to automatically set this value when no `keyDate` attribute was used. 

==== (point attribute, uuuu-9999)

applies to example(s): client12:51569

Not sure how these come out in the CSV being emitted by Nigel's migrate-from-Fedora tool.

I'm getting these out of MODS in CSV using my script like:

@encoding	@keyDate	@point	@qualifier	dateIssued
marc;;; marc	;;; 	start;;; end	;;; 	uuuu;;; 9999

I will need a process that knows converts CSV format patterns into the suggested I7 date patterns we gave our pilot client, which I can run through https://github.com/kspurgin/emendate[emendate]. In this case, something like:

 uuuu to 9999

Emendate will return the EDTF expression `/..` (Time interval with unknown start, open end -- This is currently as of 2021-06-09 being accepted by the controlled_access_terms EDTF date type as valid EDTF with strict checking and ranges enabled. It is rendered as "open start to open end", which is incorrect.)

==== date with `c` prefix recorded as `dateIssued` value

applies to example(s): client12:23046

Strip `c` prefix and map to Copyright date field

==== "Digitized" label provided on `captureDate` value

applies to example(s):

* client6:9685 (probably site-wide issue)

This label is redundant. It should be stripped out of `captureDate`

==== `dateOther` value with label included

Will be used to define client-specific date or note fields (depending on usage throughout site data) to map data into.

Will need to be stripped out of values after affecting field mapping 

=== originInfo/frequency values

applies to example(s): client12:51569

* deduplicate identical values before doing taxonomy term lookups

=== originInfo/issuance values

applies to example(s): client12:23046

Map variants to LC issuance vocabulary
