:toc:
:toc-placement!:
:toclevels: 4

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Demo site metadata profiling

toc::[]

== Counts
=== PIDS with OBJ datastream in demo: 335

http://localhost:9876/solr/collection1/select?q=fedora_datastreams_ms%3AOBJ&fl=PID,RELS_EXT_hasModel_uri_ms&rows=500&wt=csv

TODO: link to list

=== PIDS with MODS datastream in demo: 326

http://localhost:9876/solr/collection1/select?q=fedora_datastreams_ms%3AMODS&fl=PID,RELS_EXT_hasModel_uri_ms&rows=500&wt=csv

TODO: link to list

=== PIDS having both OBJ and MODS datastreams: 299

http://localhost:9876/solr/collection1/select?q=fedora_datastreams_ms%3AMODS%20AND%20fedora_datastreams_ms%3AOBJ&fl=PID,RELS_EXT_hasModel_uri_ms&rows=300&wt=csv

TODO: link to list

=== PIDS having no OBJ ds and no MODS ds: 5

http://localhost:9876/solr/collection1/select?q=-fedora_datastreams_ms%3AMODS%20AND%20-fedora_datastreams_ms%3AOBJ&fl=PID,RELS_EXT_hasModel_uri_ms&rows=300&wt=csv

* islandora:root,info:fedora/islandora:collectionCModel
* lyrdemo:image,info:fedora/islandora:collectionCModel
* lyrdemo:format,info:fedora/islandora:collectionCModel
* lyrdemo:york,info:fedora/islandora:collectionCModel
* lyrdemo:1,info:fedora/islandora:collectionCModel


=== PIDS with OBJ ds but no MODS ds: 36

http://localhost:9876/solr/collection1/select?q=-fedora_datastreams_ms%3AMODS%20AND%20fedora_datastreams_ms%3AOBJ&fl=PID,RELS_EXT_hasModel_uri_ms&rows=300&wt=csv

* lyrdemo:2185,info:fedora/islandora:newspaperPageCModel
* lyrdemo:2181,info:fedora/islandora:newspaperPageCModel
* lyrdemo:2187,info:fedora/islandora:newspaperPageCModel
* lyrdemo:2183,info:fedora/islandora:newspaperPageCModel
* lyrdemo:2191,info:fedora/islandora:newspaperPageCModel
* lyrdemo:2189,info:fedora/islandora:newspaperPageCModel
* lyrdemo:2207,info:fedora/islandora:newspaperPageCModel
* lyrdemo:2203,info:fedora/islandora:newspaperPageCModel
* lyrdemo:2215,info:fedora/islandora:newspaperPageCModel
* lyrdemo:2199,info:fedora/islandora:newspaperPageCModel
* lyrdemo:2205,info:fedora/islandora:newspaperPageCModel
* lyrdemo:2229,info:fedora/islandora:newspaperPageCModel
* lyrdemo:2213,info:fedora/islandora:newspaperPageCModel
* lyrdemo:2219,info:fedora/islandora:newspaperPageCModel
* lyrdemo:2221,info:fedora/islandora:newspaperPageCModel
* lyrdemo:2233,info:fedora/islandora:newspaperPageCModel
* lyrdemo:2241,info:fedora/islandora:newspaperPageCModel
* lyrdemo:2247,info:fedora/islandora:newspaperPageCModel
* lyrdemo:2235,info:fedora/islandora:newspaperPageCModel
* lyrdemo:2243,info:fedora/islandora:newspaperPageCModel
* lyrdemo:2245,info:fedora/islandora:newspaperPageCModel
* lyrdemo:2231,info:fedora/islandora:newspaperPageCModel
* lyrdemo:3212,info:fedora/islandora:pageCModel
* lyrdemo:3213,info:fedora/islandora:pageCModel
* lyrdemo:3206,info:fedora/islandora:pageCModel
* lyrdemo:3207,info:fedora/islandora:pageCModel
* lyrdemo:3214,info:fedora/islandora:pageCModel
* lyrdemo:3211,info:fedora/islandora:pageCModel
* lyrdemo:3205,info:fedora/islandora:pageCModel
* lyrdemo:3209,info:fedora/islandora:pageCModel
* lyrdemo:3210,info:fedora/islandora:pageCModel
* lyrdemo:3203,info:fedora/islandora:pageCModel
* lyrdemo:3204,info:fedora/islandora:pageCModel
* lyrdemo:3201,info:fedora/islandora:pageCModel
* lyrdemo:3202,info:fedora/islandora:pageCModel
* lyrdemo:3208,info:fedora/islandora:pageCModel

=== PIDS with MODS ds but no OBJ ds: 27

http://localhost:9876/solr/collection1/select?q=-fedora_datastreams_ms%3AOBJ%20AND%20fedora_datastreams_ms%3AMODS&fl=PID,RELS_EXT_hasModel_uri_ms&rows=300&wt=csv

* lyrdemo:2333,info:fedora/islandora:compoundCModel
* lyrdemo:2225,info:fedora/islandora:newspaperIssueCModel
* lyrdemo:books,info:fedora/islandora:collectionCModel
* lyrdemo:2237,info:fedora/islandora:newspaperIssueCModel
* lyrdemo:12,info:fedora/islandora:compoundCModel
* lyrdemo:2175,info:fedora/islandora:newspaperIssueCModel
* lyrdemo:2194,info:fedora/islandora:newspaperIssueCModel
* lyrdemo:2002,info:fedora/islandora:bookCModel
* lyrdemo:2174,info:fedora/islandora:newspaperCModel
* lyrdemo:2209,info:fedora/islandora:newspaperIssueCModel
* lyrdemo:29,info:fedora/islandora:compoundCModel
* lyrdemo:3090,info:fedora/islandora:bookCModel
* lyrdemo:2119,info:fedora/islandora:bookCModel
* lyrdemo:1697,info:fedora/islandora:bookCModel
* lyrdemo:3200,info:fedora/islandora:bookCModel
* lyrdemo:3194,info:fedora/islandora:collectionCModel
* lyrdemo:images,info:fedora/islandora:collectionCModel
* lyrdemo:3234,info:fedora/islandora:collectionCModel
* lyrdemo:4541,info:fedora/ir:thesisCModel
* lyrdemo:4549,info:fedora/ir:citationCModel
* lyrdemo:4550,info:fedora/ir:citationCModel
* lyrdemo:4546,info:fedora/ir:thesisCModel
* lyrdemo:4547,info:fedora/ir:citationCModel
* lyrdemo:4548,info:fedora/ir:citationCModel
* lyrdemo:4568,info:fedora/islandora:sp_basic_image
* lyrdemo:4573,info:fedora/islandora:collectionCModel
* lyrdemo:4608,info:fedora/islandora:collectionCModel

== Validation

=== Initial
==== Summary

[source]
----
19 invalid MODS files in /Users/kristina/data/islandora/demo_pilot/demo. See validation_log.txt for details.
The unique error types found across the MODS files are:
 - 7	Element '{http://www.loc.gov/mods/v3}name', attribute 'type': [facet 'enumeration'] The value '' is not an element of the set {'personal', 'corporate', 'conference', 'family'}.
 - 7	Element '{http://www.loc.gov/mods/v3}format': This element is not expected. Expected is one of ( {http://www.loc.gov/mods/v3}form, {http://www.loc.gov/mods/v3}reformattingQuality, {http://www.loc.gov/mods/v3}internetMediaType, {http://www.loc.gov/mods/v3}extent, {http://www.loc.gov/mods/v3}digitalOrigin, {http://www.loc.gov/mods/v3}note ).
 - 4	Element '{http://www.loc.gov/mods/v3}subject', attribute 'type': The attribute 'type' is not allowed.
 - 4	Element '{http://www.loc.gov/mods/v3}digitalOrigin': This element is not expected.
 - 2	Element '{http://www.loc.gov/mods/v3}url': This element is not expected. Expected is ( {http://www.loc.gov/mods/v3}holdingExternal ).
 - 2	Element '{http://www.loc.gov/mods/v3}physicalDescription': Missing child element(s). Expected is one of ( {http://www.loc.gov/mods/v3}form, {http://www.loc.gov/mods/v3}reformattingQuality, {http://www.loc.gov/mods/v3}internetMediaType, {http://www.loc.gov/mods/v3}extent, {http://www.loc.gov/mods/v3}digitalOrigin, {http://www.loc.gov/mods/v3}note ).
 - 2	Element '{http://www.loc.gov/mods/v3}physicalDescription': Character content other than whitespace is not allowed because the content type is 'element-only'.
 - 2	Element '{http://www.loc.gov/mods/v3}physicalDescription', attribute 'authority': The attribute 'authority' is not allowed.
 - 2	Element '{http://www.loc.gov/mods/v3}namePart': This element is not expected. Expected is one of ( {http://www.loc.gov/mods/v3}topic, {http://www.loc.gov/mods/v3}geographic, {http://www.loc.gov/mods/v3}temporal, {http://www.loc.gov/mods/v3}titleInfo, {http://www.loc.gov/mods/v3}name, {http://www.loc.gov/mods/v3}geographicCode, {http://www.loc.gov/mods/v3}hierarchicalGeographic, {http://www.loc.gov/mods/v3}cartographics, {http://www.loc.gov/mods/v3}occupation, {http://www.loc.gov/mods/v3}genre ).
 - 2	Element '{http://www.loc.gov/mods/v3}name', attribute 'usage': The value '' does not match the fixed value constraint 'primary'.
 ----
 
==== Detail

[source]
----
# Logfile created on 2022-03-16 14:59:14 -0400 by logger.rb/v1.4.2
E, [2022-03-16T15:05:24.113224 #20223] ERROR -- : MODS VALIDATION: invalid MODS: /Users/kristina/data/islandora/demo_pilot/demo/lyrdemo:3090.xml: 9:0: ERROR: Element '{http://www.loc.gov/mods/v3}name', attribute 'type': [facet 'enumeration'] The value '' is not an element of the set {'personal', 'corporate', 'conference', 'family'}.
E, [2022-03-16T15:05:24.113319 #20223] ERROR -- : MODS VALIDATION: invalid MODS: /Users/kristina/data/islandora/demo_pilot/demo/lyrdemo:3090.xml: 15:0: ERROR: Element '{http://www.loc.gov/mods/v3}name', attribute 'type': [facet 'enumeration'] The value '' is not an element of the set {'personal', 'corporate', 'conference', 'family'}.
E, [2022-03-16T15:05:24.113417 #20223] ERROR -- : MODS VALIDATION: invalid MODS: /Users/kristina/data/islandora/demo_pilot/demo/lyrdemo:3090.xml: 86:0: ERROR: Element '{http://www.loc.gov/mods/v3}name', attribute 'type': [facet 'enumeration'] The value '' is not an element of the set {'personal', 'corporate', 'conference', 'family'}.
E, [2022-03-16T15:05:24.113502 #20223] ERROR -- : MODS VALIDATION: invalid MODS: /Users/kristina/data/islandora/demo_pilot/demo/lyrdemo:3090.xml: 98:0: ERROR: Element '{http://www.loc.gov/mods/v3}url': This element is not expected. Expected is ( {http://www.loc.gov/mods/v3}holdingExternal ).
E, [2022-03-16T15:05:24.114316 #20223] ERROR -- : MODS VALIDATION: invalid MODS: /Users/kristina/data/islandora/demo_pilot/demo/lyrdemo:2577.xml: 16:0: ERROR: Element '{http://www.loc.gov/mods/v3}format': This element is not expected. Expected is one of ( {http://www.loc.gov/mods/v3}form, {http://www.loc.gov/mods/v3}reformattingQuality, {http://www.loc.gov/mods/v3}internetMediaType, {http://www.loc.gov/mods/v3}extent, {http://www.loc.gov/mods/v3}digitalOrigin, {http://www.loc.gov/mods/v3}note ).
E, [2022-03-16T15:05:24.118939 #20223] ERROR -- : MODS VALIDATION: invalid MODS: /Users/kristina/data/islandora/demo_pilot/demo/lyrdemo:3091.xml: 9:0: ERROR: Element '{http://www.loc.gov/mods/v3}name', attribute 'type': [facet 'enumeration'] The value '' is not an element of the set {'personal', 'corporate', 'conference', 'family'}.
E, [2022-03-16T15:05:24.119004 #20223] ERROR -- : MODS VALIDATION: invalid MODS: /Users/kristina/data/islandora/demo_pilot/demo/lyrdemo:3091.xml: 15:0: ERROR: Element '{http://www.loc.gov/mods/v3}name', attribute 'type': [facet 'enumeration'] The value '' is not an element of the set {'personal', 'corporate', 'conference', 'family'}.
E, [2022-03-16T15:05:24.119048 #20223] ERROR -- : MODS VALIDATION: invalid MODS: /Users/kristina/data/islandora/demo_pilot/demo/lyrdemo:3091.xml: 86:0: ERROR: Element '{http://www.loc.gov/mods/v3}name', attribute 'type': [facet 'enumeration'] The value '' is not an element of the set {'personal', 'corporate', 'conference', 'family'}.
E, [2022-03-16T15:05:24.119093 #20223] ERROR -- : MODS VALIDATION: invalid MODS: /Users/kristina/data/islandora/demo_pilot/demo/lyrdemo:3091.xml: 98:0: ERROR: Element '{http://www.loc.gov/mods/v3}url': This element is not expected. Expected is ( {http://www.loc.gov/mods/v3}holdingExternal ).
E, [2022-03-16T15:05:24.127699 #20223] ERROR -- : MODS VALIDATION: invalid MODS: /Users/kristina/data/islandora/demo_pilot/demo/lyrdemo:2558.xml: 15:0: ERROR: Element '{http://www.loc.gov/mods/v3}format': This element is not expected. Expected is one of ( {http://www.loc.gov/mods/v3}form, {http://www.loc.gov/mods/v3}reformattingQuality, {http://www.loc.gov/mods/v3}internetMediaType, {http://www.loc.gov/mods/v3}extent, {http://www.loc.gov/mods/v3}digitalOrigin, {http://www.loc.gov/mods/v3}note ).
E, [2022-03-16T15:05:24.138538 #20223] ERROR -- : MODS VALIDATION: invalid MODS: /Users/kristina/data/islandora/demo_pilot/demo/lyrdemo:2312.xml: 10:0: ERROR: Element '{http://www.loc.gov/mods/v3}format': This element is not expected. Expected is one of ( {http://www.loc.gov/mods/v3}form, {http://www.loc.gov/mods/v3}reformattingQuality, {http://www.loc.gov/mods/v3}internetMediaType, {http://www.loc.gov/mods/v3}extent, {http://www.loc.gov/mods/v3}digitalOrigin, {http://www.loc.gov/mods/v3}note ).
E, [2022-03-16T15:05:24.166005 #20223] ERROR -- : MODS VALIDATION: invalid MODS: /Users/kristina/data/islandora/demo_pilot/demo/lyrdemo:4570.xml: 17:0: ERROR: Element '{http://www.loc.gov/mods/v3}digitalOrigin': This element is not expected.
E, [2022-03-16T15:05:24.172336 #20223] ERROR -- : MODS VALIDATION: invalid MODS: /Users/kristina/data/islandora/demo_pilot/demo/lyrdemo:6.xml: 6:0: ERROR: Element '{http://www.loc.gov/mods/v3}name', attribute 'usage': The value '' does not match the fixed value constraint 'primary'.
E, [2022-03-16T15:05:24.173297 #20223] ERROR -- : MODS VALIDATION: invalid MODS: /Users/kristina/data/islandora/demo_pilot/demo/lyrdemo:4571.xml: 17:0: ERROR: Element '{http://www.loc.gov/mods/v3}digitalOrigin': This element is not expected.
E, [2022-03-16T15:05:24.178223 #20223] ERROR -- : MODS VALIDATION: invalid MODS: /Users/kristina/data/islandora/demo_pilot/demo/lyrdemo:4568.xml: 17:0: ERROR: Element '{http://www.loc.gov/mods/v3}digitalOrigin': This element is not expected.
E, [2022-03-16T15:05:24.185339 #20223] ERROR -- : MODS VALIDATION: invalid MODS: /Users/kristina/data/islandora/demo_pilot/demo/lyrdemo:4569.xml: 17:0: ERROR: Element '{http://www.loc.gov/mods/v3}digitalOrigin': This element is not expected.
E, [2022-03-16T15:05:24.186595 #20223] ERROR -- : MODS VALIDATION: invalid MODS: /Users/kristina/data/islandora/demo_pilot/demo/lyrdemo:4541.xml: 41:0: ERROR: Element '{http://www.loc.gov/mods/v3}physicalDescription', attribute 'authority': The attribute 'authority' is not allowed.
E, [2022-03-16T15:05:24.186664 #20223] ERROR -- : MODS VALIDATION: invalid MODS: /Users/kristina/data/islandora/demo_pilot/demo/lyrdemo:4541.xml: 41:0: ERROR: Element '{http://www.loc.gov/mods/v3}physicalDescription': Character content other than whitespace is not allowed because the content type is 'element-only'.
E, [2022-03-16T15:05:24.186711 #20223] ERROR -- : MODS VALIDATION: invalid MODS: /Users/kristina/data/islandora/demo_pilot/demo/lyrdemo:4541.xml: 41:0: ERROR: Element '{http://www.loc.gov/mods/v3}physicalDescription': Missing child element(s). Expected is one of ( {http://www.loc.gov/mods/v3}form, {http://www.loc.gov/mods/v3}reformattingQuality, {http://www.loc.gov/mods/v3}internetMediaType, {http://www.loc.gov/mods/v3}extent, {http://www.loc.gov/mods/v3}digitalOrigin, {http://www.loc.gov/mods/v3}note ).
E, [2022-03-16T15:05:24.189643 #20223] ERROR -- : MODS VALIDATION: invalid MODS: /Users/kristina/data/islandora/demo_pilot/demo/lyrdemo:3238.xml: 26:0: ERROR: Element '{http://www.loc.gov/mods/v3}subject', attribute 'type': The attribute 'type' is not allowed.
E, [2022-03-16T15:05:24.189738 #20223] ERROR -- : MODS VALIDATION: invalid MODS: /Users/kristina/data/islandora/demo_pilot/demo/lyrdemo:3238.xml: 29:0: ERROR: Element '{http://www.loc.gov/mods/v3}subject', attribute 'type': The attribute 'type' is not allowed.
E, [2022-03-16T15:05:24.189780 #20223] ERROR -- : MODS VALIDATION: invalid MODS: /Users/kristina/data/islandora/demo_pilot/demo/lyrdemo:3238.xml: 32:0: ERROR: Element '{http://www.loc.gov/mods/v3}subject', attribute 'type': The attribute 'type' is not allowed.
E, [2022-03-16T15:05:24.189820 #20223] ERROR -- : MODS VALIDATION: invalid MODS: /Users/kristina/data/islandora/demo_pilot/demo/lyrdemo:3238.xml: 33:0: ERROR: Element '{http://www.loc.gov/mods/v3}namePart': This element is not expected. Expected is one of ( {http://www.loc.gov/mods/v3}topic, {http://www.loc.gov/mods/v3}geographic, {http://www.loc.gov/mods/v3}temporal, {http://www.loc.gov/mods/v3}titleInfo, {http://www.loc.gov/mods/v3}name, {http://www.loc.gov/mods/v3}geographicCode, {http://www.loc.gov/mods/v3}hierarchicalGeographic, {http://www.loc.gov/mods/v3}cartographics, {http://www.loc.gov/mods/v3}occupation, {http://www.loc.gov/mods/v3}genre ).
E, [2022-03-16T15:05:24.194100 #20223] ERROR -- : MODS VALIDATION: invalid MODS: /Users/kristina/data/islandora/demo_pilot/demo/lyrdemo:4344.xml: 33:0: ERROR: Element '{http://www.loc.gov/mods/v3}subject', attribute 'type': The attribute 'type' is not allowed.
E, [2022-03-16T15:05:24.194156 #20223] ERROR -- : MODS VALIDATION: invalid MODS: /Users/kristina/data/islandora/demo_pilot/demo/lyrdemo:4344.xml: 34:0: ERROR: Element '{http://www.loc.gov/mods/v3}namePart': This element is not expected. Expected is one of ( {http://www.loc.gov/mods/v3}topic, {http://www.loc.gov/mods/v3}geographic, {http://www.loc.gov/mods/v3}temporal, {http://www.loc.gov/mods/v3}titleInfo, {http://www.loc.gov/mods/v3}name, {http://www.loc.gov/mods/v3}geographicCode, {http://www.loc.gov/mods/v3}hierarchicalGeographic, {http://www.loc.gov/mods/v3}cartographics, {http://www.loc.gov/mods/v3}occupation, {http://www.loc.gov/mods/v3}genre ).
E, [2022-03-16T15:05:24.199494 #20223] ERROR -- : MODS VALIDATION: invalid MODS: /Users/kristina/data/islandora/demo_pilot/demo/lyrdemo:4591.xml: 6:0: ERROR: Element '{http://www.loc.gov/mods/v3}name', attribute 'type': [facet 'enumeration'] The value '' is not an element of the set {'personal', 'corporate', 'conference', 'family'}.
E, [2022-03-16T15:05:24.199554 #20223] ERROR -- : MODS VALIDATION: invalid MODS: /Users/kristina/data/islandora/demo_pilot/demo/lyrdemo:4591.xml: 6:0: ERROR: Element '{http://www.loc.gov/mods/v3}name', attribute 'usage': The value '' does not match the fixed value constraint 'primary'.
E, [2022-03-16T15:05:24.201290 #20223] ERROR -- : MODS VALIDATION: invalid MODS: /Users/kristina/data/islandora/demo_pilot/demo/lyrdemo:4546.xml: 32:0: ERROR: Element '{http://www.loc.gov/mods/v3}physicalDescription', attribute 'authority': The attribute 'authority' is not allowed.
E, [2022-03-16T15:05:24.201348 #20223] ERROR -- : MODS VALIDATION: invalid MODS: /Users/kristina/data/islandora/demo_pilot/demo/lyrdemo:4546.xml: 32:0: ERROR: Element '{http://www.loc.gov/mods/v3}physicalDescription': Character content other than whitespace is not allowed because the content type is 'element-only'.
E, [2022-03-16T15:05:24.201387 #20223] ERROR -- : MODS VALIDATION: invalid MODS: /Users/kristina/data/islandora/demo_pilot/demo/lyrdemo:4546.xml: 32:0: ERROR: Element '{http://www.loc.gov/mods/v3}physicalDescription': Missing child element(s). Expected is one of ( {http://www.loc.gov/mods/v3}form, {http://www.loc.gov/mods/v3}reformattingQuality, {http://www.loc.gov/mods/v3}internetMediaType, {http://www.loc.gov/mods/v3}extent, {http://www.loc.gov/mods/v3}digitalOrigin, {http://www.loc.gov/mods/v3}note ).
E, [2022-03-16T15:05:24.216450 #20223] ERROR -- : MODS VALIDATION: invalid MODS: /Users/kristina/data/islandora/demo_pilot/demo/changeme:1.xml: 11:0: ERROR: Element '{http://www.loc.gov/mods/v3}format': This element is not expected. Expected is one of ( {http://www.loc.gov/mods/v3}form, {http://www.loc.gov/mods/v3}reformattingQuality, {http://www.loc.gov/mods/v3}internetMediaType, {http://www.loc.gov/mods/v3}extent, {http://www.loc.gov/mods/v3}digitalOrigin, {http://www.loc.gov/mods/v3}note ).
E, [2022-03-16T15:05:24.219241 #20223] ERROR -- : MODS VALIDATION: invalid MODS: /Users/kristina/data/islandora/demo_pilot/demo/lyrdemo:2557.xml: 16:0: ERROR: Element '{http://www.loc.gov/mods/v3}format': This element is not expected. Expected is one of ( {http://www.loc.gov/mods/v3}form, {http://www.loc.gov/mods/v3}reformattingQuality, {http://www.loc.gov/mods/v3}internetMediaType, {http://www.loc.gov/mods/v3}extent, {http://www.loc.gov/mods/v3}digitalOrigin, {http://www.loc.gov/mods/v3}note ).
E, [2022-03-16T15:05:24.221410 #20223] ERROR -- : MODS VALIDATION: invalid MODS: /Users/kristina/data/islandora/demo_pilot/demo/changeme:2.xml: 10:0: ERROR: Element '{http://www.loc.gov/mods/v3}format': This element is not expected. Expected is one of ( {http://www.loc.gov/mods/v3}form, {http://www.loc.gov/mods/v3}reformattingQuality, {http://www.loc.gov/mods/v3}internetMediaType, {http://www.loc.gov/mods/v3}extent, {http://www.loc.gov/mods/v3}digitalOrigin, {http://www.loc.gov/mods/v3}note ).
E, [2022-03-16T15:05:24.226805 #20223] ERROR -- : MODS VALIDATION: invalid MODS: /Users/kristina/data/islandora/demo_pilot/demo/lyrdemo:2578.xml: 15:0: ERROR: Element '{http://www.loc.gov/mods/v3}format': This element is not expected. Expected is one of ( {http://www.loc.gov/mods/v3}form, {http://www.loc.gov/mods/v3}reformattingQuality, {http://www.loc.gov/mods/v3}internetMediaType, {http://www.loc.gov/mods/v3}extent, {http://www.loc.gov/mods/v3}digitalOrigin, {http://www.loc.gov/mods/v3}note ).
----
